"""Knowledge base: skills that Indian job ads for Training Manager / RSM /
Trainer / L&D Manager roles ask for, plus how to learn each one.

Each entry:
  key      -> canonical skill name shown in the report
  aliases  -> words/phrases that mean this skill in a job description
  why      -> one line on why interviewers ask for it
  learn    -> concrete, mostly-free ways to learn it
  proof    -> what to put on the resume / say in the interview once learned
"""

SKILLS = [
    # ---------------- L&D / Training core ----------------
    dict(key="ADDIE instructional design", roles=["trainer", "training manager", "l&d"],
         aliases=["addie", "instructional design", "instructional designer", "curriculum design",
                  "content design", "courseware", "module design", "learning design", "id"],
         why="Every L&D/Training Manager JD wants a repeatable design model. Interviewers ask 'how do you build a program from scratch?'",
         learn=["Free: ATD 'ADDIE model' article + Cathy Moore's Action Mapping blog (2 hrs read)",
                "Coursera - 'Instructional Design Foundations and Applications' (Univ. of Illinois), audit free",
                "Do it: rebuild one of your NHT Day 1-3 sessions as a formal ADDIE doc (Analyse/Design/Develop/Implement/Evaluate)"],
         link="https://www.cathy-moore.com/action-mapping-a-no-nonsense-approach-to-design/ ",
         proof="Say: 'I redesigned NHT Day 1-3 using ADDIE; analysis showed X gap, redesign cut ramp time by Y%'",
         adjacent=["curriculum", "nht", "day 1", "module", "content", "training program",
                   "training track", "courseware", "session design", "syllabus"],
         tools=["AI: ChatGPT/Gemini - paste a session plan, ask it to 'rewrite using ADDIE (Analyse/Design/Develop/Implement/Evaluate) with outputs for each phase'",
                "Free software: H5P (inside Moodle) or Canva Docs to lay out the 5-phase design map",
                "Template: download a free ADDIE template from ATD/InstructionalDesign.org and fill it with your NHT Day 1-3"]),

    dict(key="Kirkpatrick training evaluation (L1-L4)", roles=["trainer", "training manager", "l&d"],
         aliases=["kirkpatrick", "training effectiveness", "l1", "l2", "l3", "l4",
                  "training evaluation", "roi of training", "phillips roi", "impact measurement"],
         why="This is THE most common rejection reason for trainers moving to manager: you can deliver, but can't prove business impact.",
         learn=["Free: Kirkpatrick Partners website 'The New World Kirkpatrick Model' overview",
                "YouTube: 'Kirkpatrick 4 Levels explained' (20 min)",
                "Do it: build a 1-page L1(feedback) / L2(quiz score) / L3(on-floor behaviour) / L4(business metric) sheet for your own NHT batches"],
         link="https://www.kirkpatrickpartners.com/the-kirkpatrick-model/ ",
         proof="Carry a printed L1-L4 sheet from a real batch to the interview. Instant credibility.",
         adjacent=["feedback", "quiz", "assessment", "score", "report", "effectness",
                   "batch result", "completion", "dashboard", "mis"],
         tools=["AI: ask ChatGPT 'From this batch data (attendance, quiz %, on-floor audit, business KPI), build a Kirkpatrick L1-L4 one-pager'",
                "Free tool: Google Forms (L1 reaction) + your existing quiz scores (L2) + a simple Excel tracker (L3/L4)",
                "Template: Kirkpatrick 'Level 1-4' free worksheet; map each level to a number you already collect"]),

    dict(key="TNI / TNA (Training Needs Identification)", roles=["training manager", "l&d"],
         aliases=["tni", "tna", "training need", "needs identification", "needs analysis",
                  "skill gap analysis", "competency mapping", "capability building"],
         why="Manager-level JDs expect you to decide WHAT training is needed, not just run it.",
         learn=["Free: SHRM / ATD articles on 'Training Needs Analysis template'",
                "Do it: run a TNI on your 12 trainers - survey + performance data + manager interviews - and keep the output as a work sample"],
         link="https://www.shrm.org/topics-tools/hr-topics/learning-development/training-needs-assessment ",
         proof="Show the TNI doc: data sources, gaps found, programs you launched because of it.",
         adjacent=["gap", "survey", "performance", "coaching", "capability", "audit", "data"],
         tools=["AI: ChatGPT - 'From these 6 trainer performance issues, draft a TNI survey (10 questions) + a manager interview guide'",
                "Free tool: Google Forms to run the survey + Google Sheets to tally gaps; or Microsoft Forms",
                "Method: 3 sources = survey + performance data + manager interview (the '3-lens' TNI)"]),

    dict(key="LMS administration", roles=["trainer", "training manager", "l&d"],
         aliases=["lms", "learning management system", "moodle", "cornerstone", "successfactors",
                  "docebo", "talentlms", "workday learning", "degreed", "litmos", "saba"],
         why="Almost every L&D JD lists an LMS. 'Never used one' is an instant filter-out.",
         learn=["Free hands-on: create a free Moodle sandbox (moodle.org demo / MoodleCloud free tier) and build one course end to end",
                "Free: TalentLMS free plan (up to 5 users) - upload content, enrol users, pull completion reports",
                "LinkedIn Learning: 'Learning Management Systems' basics"],
         link="https://www.talentlms.com/free-lms/ ",
         proof="'I administered courses on <LMS>: enrolment, completion tracking, compliance reporting.'",
         adjacent=["enrol", "enrollment", "tracker", "completion", "certification", "attendance",
                   "mis", "dashboard", "record"],
         tools=["Free LMS: TalentLMS free (5 users) or MoodleCloud free - build ONE real course end to end",
                "AI: ChatGPT - 'Write the course outline, quiz questions and completion certificate text for a 1-hour NHT module'",
                "Watch: 'Moodle for beginners' (YouTube, 1 hr) to learn enrolment, cohorts, completion tracking"]),

    dict(key="e-learning authoring (Articulate / Rise / Captivate)", roles=["trainer", "l&d"],
         aliases=["articulate", "storyline", "rise 360", "captivate", "camtasia", "authoring tool",
                  "elearning", "e-learning", "scorm", "digital content creation", "vyond", "canva"],
         why="Digital content creation is now standard in L&D JDs even for classroom trainers.",
         learn=["Articulate 360 free 30-day trial - build ONE Rise course (your NHT Day 1) in a weekend",
                "Free alternative: Canva + Camtasia trial, or free H5P inside Moodle",
                "YouTube: 'Articulate Rise 360 full tutorial for beginners'"],
         link="https://www.articulate.com/products/rise.php ",
         proof="Keep a shareable link to one finished Rise course as your portfolio.",
         adjacent=["content", "module", "courseware", "ppt", "presentation", "nht", "deck",
                   "material", "job aid", "sop"],
         tools=["Paid (free trial): Articulate 360 (Rise 360 + Storyline) - 30 days, enough to build 2-3 courses",
                "Free: Canva (course visuals) + CapCut/Clipchamp (talking-head video) + H5P (interactive quizzes in Moodle)",
                "AI: ChatGPT - 'Turn this NHT Day-1 classroom outline into a Rise 360 block-by-block course plan'"]),

    dict(key="Train-the-Trainer / facilitation certification", roles=["trainer", "training manager", "l&d"],
         aliases=["train the trainer", "ttt", "facilitation", "facilitator", "certified trainer",
                  "coaching certification", "icf", "mbti", "psychometric"],
         why="A named certification gets you past HR screening for Training Manager roles.",
         learn=["Low cost: 'Train the Trainer' on Udemy (frequent Rs.400-600 sales) with certificate",
                "Higher value: ATD Master Trainer / CIPD L3 (paid) - only if company sponsors",
                "Free: Harvard ManageMentor style facilitation guides + practice recording yourself"],
         link="https://www.udemy.com/courses/search/?q=train+the+trainer&price=price-free ",
         proof="Put the certificate name on your Naukri headline - recruiters search for it.",
         adjacent=["trainer", "facilitat", "coach", "session", "demo", "deliver", "nht",
                   "conduct", "session"],
         tools=["Low-cost cert: Udemy 'Train the Trainer' (Rs.400-600 in sales) - gives a certificate for Naukri",
                "Free: record yourself delivering a 10-min session on your phone, watch for fillers, re-record",
                "AI: ChatGPT - 'Generate a 10-minute trainer facilitation script + 5 engagement questions for topic X'"]),

    dict(key="Coaching & feedback models (GROW, SBI)", roles=["trainer", "training manager", "l&d", "rsm"],
         aliases=["coaching", "mentoring", "grow model", "sbi feedback", "one on one",
                  "performance coaching", "capability coach", "hand holding"],
         why="Manager interviews always include 'how do you coach an underperformer?'",
         learn=["Free: GROW model explainer (MindTools) + SBI feedback framework (CCL) - 1 hr total",
                "Do it: run 4 structured GROW coaching sessions with your own trainers, note outcomes"],
         link="https://www.mindtools.com/pages/article/newLDR_89.htm ",
         proof="Have 2 stories ready: an underperformer you coached, and the measurable change.",
         adjacent=["coach", "one on one", "mentor", "feedback", "trainer", "capability", "review"],
         tools=["Framework: GROW (Goal- Reality- Options- Will) + SBI (Situation-Behaviour-Impact) feedback",
                "AI: ChatGPT - 'Act as my coaching log: here is an underperformer's issue, draft a GROW session plan + an SBI feedback script'",
                "Free: CareerPlus /your own notes app to log 4 coaching sessions with before/after numbers"]),

    dict(key="Content / SOP documentation", roles=["trainer", "training manager", "l&d"],
         aliases=["sop", "documentation", "job aid", "knowledge base", "process documentation",
                  "content development", "collateral", "training material"],
         why="Cheap to demonstrate, frequently listed, and you already do it.",
         learn=["Free: Google 'Nielsen Norman job aid design'; keep material to 1 page per task",
                "Do it: convert 3 recurring processes (MIS Update, Attendance Regularization, Visit Barge) into 1-page SOPs"],
         link="https://www.nngroup.com/articles/job-aids/ ",
         proof="Bring the SOP pack; it doubles as proof of documentation skill.",
         adjacent=["sop", "document", "job aid", "process", "content", "nht", "material", "checklist"],
         tools=["Free: Google Docs / Word - one-page SOP per process (MIS Update, Attendance Regularization, Visit Barge)",
                "AI: ChatGPT - 'Convert this messy process note into a 1-page SOP with steps, owner, checklist'",
                "Tool: draw.io (free) or Canva to make a simple process flow diagram"]),

    # ---------------- Data / reporting ----------------
    dict(key="Excel advanced (pivots, lookups, dashboards)", roles=["trainer", "training manager", "l&d", "rsm"],
         aliases=["excel", "advanced excel", "pivot", "vlookup", "xlookup", "spreadsheet",
                  "ms office", "mis", "macro", "vba"],
         why="Named in nearly every JD in all 4 role families. Weak Excel = weak MIS = rejection.",
         learn=["Free: ExcelJet + Chandoo.org; then Microsoft's free 'Excel for Windows training'",
                "YouTube: Leila Gharani 'Excel Pivot Tables' + 'XLOOKUP' (3 hrs total)",
                "Do it: build one live dashboard of your 12 trainers' daily activity with pivots + slicers"],
         link="https://support.microsoft.com/en-us/training ",
         proof="Screenshot of your dashboard on your laptop, ready to show.",
         adjacent=["excel", "tracker", "mis", "dashboard", "pivot", "lookup", "vlookup", "report", "data"],
         tools=["Free: Microsoft Excel (free web version) or Google Sheets; YouTube Leila Gharani 'Pivot Tables' + 'XLOOKUP'",
                "AI: ChatGPT - 'I have this trainer-activity table, write the exact Excel formula for a daily dashboard with slicers'",
                "Practice file: build a live 12-trainer daily MIS with Pivot + slicer in one sitting"]),

    dict(key="Power BI / data visualisation", roles=["training manager", "l&d", "rsm"],
         aliases=["power bi", "powerbi", "tableau", "dashboard", "data visualization",
                  "data visualisation", "analytics", "reporting", "business intelligence", "sql"],
         why="Increasingly listed for manager roles - they want insight, not raw sheets.",
         learn=["Free: Power BI Desktop is free; Microsoft Learn 'Get started with Power BI' path (~6 hrs)",
                "Do it: load your trainer activity CSV into Power BI, make a 1-page report"],
         link="https://learn.microsoft.com/en-us/training/powerplatform/power-bi/ ",
         proof="'I publish a weekly Power BI report on training throughput and attendance.'",
         adjacent=["power bi", "dashboard", "mis", "excel", "report", "visual", "chart", "data"],
         tools=["Free: Power BI Desktop (full free) - Microsoft Learn 'Get started with Power BI' path",
                "AI: ChatGPT - 'I have a CSV of trainer activity, suggest the 5 best Power BI visuals for a weekly L&D report'",
                "Free alt: Google Looker Studio (cloud BI, no install) if Power BI feels heavy"]),

    dict(key="Learning analytics / MIS reporting", roles=["training manager", "l&d"],
         aliases=["learning analytics", "training mis", "dashboard reporting", "metrics",
                  "kpi", "scorecard", "throughput", "attrition analysis"],
         why="Bridges your current MIS work to manager-level language.",
         learn=["Free: read 'training metrics that matter' (ATD) - learn the vocabulary: fill rate, throughput, TAT, certification %, attrition-linked-to-training",
                "Do it: rename your existing MIS columns to these industry terms"],
         link="https://www.td.org/insights/what-are-the-most-important-training-metrics ",
         proof="Speak in metrics: 'batch throughput 92%, certification pass 88%, D30 attrition down 6%'.",
         adjacent=["mis", "dashboard", "metric", "report", "data", "excel", "power bi", "tracking"],
         tools=["Vocabulary: ATD 'training metrics that matter' - fill rate, throughput, TAT, certification %, attrition-linked",
                "AI: ChatGPT - 'From my MIS columns (attendance, score, completion), suggest industry-standard metric names + a one-line definition each'",
                "Free: rename your existing MIS headers to these terms; same data, manager-level language"]),

    # ---------------- Sales / RSM ----------------
    dict(key="Sales target ownership & pipeline management", roles=["rsm"],
         aliases=["sales target", "revenue target", "quota", "pipeline", "funnel", "lead generation",
                  "business development", "achievement", "top line", "gmv", "aum", "sales planning"],
         why="RSM shortlisting is almost purely 'have you carried a number and hit it?'",
         learn=["Free: HubSpot Academy 'Sales Management' + 'Inbound Sales' (free certificates)",
                "Do it: if you have no quota history, target a Sales Trainer or Sales Capability role first - it's the realistic bridge from L&D to RSM"],
         link="https://academy.hubspot.com/courses/sales-management ",
         proof="Numbers only: target vs achieved vs %, for 4+ quarters. Without this, RSM is a low-probability path.",
         tools=["Free: HubSpot Academy 'Sales Management' + 'Inbound Sales' (free certificates for Naukri)",
                "AI: ChatGPT - 'I am an L&D person moving to sales; simulate a quarterly target-review conversation and coach me'",
                "Bridge role: target Sales Trainer / Sales Capability first - uses your training skills AND gets you quota exposure"]),

    dict(key="Channel / distributor management", roles=["rsm"],
         aliases=["channel", "distributor", "dealer", "franchise", "partner management",
                  "channel sales", "territory management", "beat plan", "route to market", "gt", "mt"],
         why="Regional roles are mostly about managing partners, not direct selling.",
         learn=["Free: YouTube 'FMCG channel sales / beat plan explained'",
                "Read: 'Route to Market' basics; learn terms - ROI of distributor, coverage, TLSD, must-sell SKUs"],
         link="https://www.youtube.com/results?search_query=fmcg+channel+sales+beat+plan+explained ",
         proof="Be able to explain how you'd plan a territory's coverage and distributor ROI.",
         tools=["Free: YouTube 'FMCG channel sales / beat plan explained' (Hindi/English mixes available)",
                "AI: ChatGPT - 'Explain distributor ROI, coverage %, TLSD, must-sell SKU in simple terms with an example'",
                "Read: a basic 'Route to Market' article; learn the 6-8 terms sales managers use"]),

    dict(key="CRM tools (Salesforce / Zoho / LeadSquared)", roles=["rsm"],
         aliases=["crm", "salesforce", "zoho", "leadsquared", "hubspot", "sfdc", "sales force automation", "sfa"],
         why="Standard tool requirement in sales-side JDs.",
         learn=["Free: Salesforce Trailhead (gamified, gives badges you can list on Naukri)",
                "Free: Zoho CRM free edition - create leads, stages, reports"],
         link="https://trailhead.salesforce.com/en/content/learn/trails/administrator_beginner ",
         proof="List Trailhead badges/superbadges on your resume.",
         tools=["Free: Salesforce Trailhead (gamified, gives badges) - do 'Admin Beginner' trail",
                "Free: Zoho CRM free edition - create leads, stages, automate a follow-up",
                "AI: ChatGPT - 'Explain Salesforce lead/opportunity/account objects with a training-team analogy'"]),

    dict(key="Team leadership & performance management", roles=["rsm", "training manager", "l&d"],
         aliases=["team handling", "team management", "span of control", "people management",
                  "performance management", "pip", "appraisal", "stakeholder management",
                  "leadership", "managing managers", "supervisory", "team of",
                  "coordinate a team", "trainer team", "team handling"],
         why="The single biggest gap when moving from individual trainer to manager.",
         learn=["Free: Coursera 'Managing Talent' / 'Leading People and Teams' (audit free)",
                "Do it: document that you already coordinate 12 trainers - that IS span of control. Quantify it."],
         link="https://www.coursera.org/learn/leading-teams ",
         proof="'I coordinate a 12-member trainer team: rostering, daily activity governance, capability reviews.'",
         adjacent=["team", "trainer", "coordinate", "12", "roster", "governance", "span of control", "lead"],
         tools=["Free: Coursera 'Leading People and Teams' (audit free) - 4 modules on leading teams",
                "AI: ChatGPT - 'I manage 12 trainers; draft a weekly 1:1 cadence + a performance improvement plan template'",
                "Framework: RACI for who-owns-what; write one for your trainer team's weekly ops"]),

    # ---------------- Cross-cutting ----------------
    dict(key="Stakeholder / business partnering", roles=["training manager", "l&d", "rsm"],
         aliases=["stakeholder", "business partner", "hrbp", "senior management", "leadership connect",
                  "cross functional", "influence", "governance", "wbr", "mbr", "review deck"],
         why="Manager roles are 60% managing upward and sideways.",
         learn=["Free: read on RACI + running WBR/MBR governance calls",
                "Do it: start sending a weekly written summary to your manager with insight, not just data (you already do the WhatsApp update - formalise it)"],
         link="https://www.atlassian.com/work-management/project-planning/raci ",
         proof="Bring a sample WBR deck you own.",
         adjacent=["stakeholder", "manager", "update", "whatsapp", "report", "governance", "partner", "wbr", "mbr"],
         tools=["Free: PowerPoint / Google Slides - build one WBR (weekly business review) deck from your MIS",
                "AI: ChatGPT - 'Turn these raw MIS numbers into a 1-page stakeholder update with 3 insights and 1 ask'",
                "Framework: RACI + the 'insight not data' rule (you already do the WhatsApp update - formalise it)"]),

    dict(key="Onboarding / new hire training programme design", roles=["trainer", "training manager", "l&d"],
         aliases=["onboarding", "induction", "new hire", "nht", "fresher training", "ojt",
                  "on the job training", "nesting", "ramp up", "certification process"],
         why="Your strongest existing asset - NHT Day 1-12. Most candidates cannot show a 12-day structured programme.",
         learn=["Nothing to learn - package it: write a 1-page NHT programme architecture (days, objectives, assessments, certification gates, ramp metrics)"],
         link="https://www.shrm.org/topics-tools/hr-topics/employee-relations/onboarding ",
         proof="Lead with this. 'I own a 12-day NHT plus 3-day technical curriculum for a 12-trainer team.'",
         adjacent=["nht", "day 1", "new hire", "induction", "ramp", "curriculum", "training program"],
         tools=["Free: draw.io or Canva - map your NHT Day 1-12 as a visual curriculum architecture",
                "AI: ChatGPT - 'From my NHT Day 1-12 notes, produce a 1-page programme architecture (objectives, assessments, certification gate, ramp metric)'",
                "Nothing new to learn - just PACKAGE what you already run into a one-pager"]),

    dict(key="Compliance / audit readiness of training records", roles=["training manager", "l&d"],
         aliases=["compliance", "audit", "regulatory", "iso", "documentation audit",
                  "attendance regularization", "record keeping", "quality audit", "coso"],
         why="BFSI/BPO L&D managers are judged on audit-clean records.",
         learn=["Free: learn your industry's training-record retention rules; build a simple audit checklist",
                "Do it: run one mock audit on your own batch records and fix the gaps"],
         link="https://www.iso.org/iso-9001-quality-management.html ",
         proof="'Zero audit observations on training records for N quarters.'",
         tools=["Free: read your industry's training-record retention rules (ISO 9001 basics)",
                "AI: ChatGPT - 'From my batch record folder, draft a simple audit checklist (what an auditor checks)'",
                "Do it: run one mock audit on your own records, fix gaps, keep the checklist as proof"]),

    dict(key="Communication & business English / presentation", roles=["trainer", "training manager", "l&d", "rsm"],
         aliases=["communication", "presentation skills", "verbal", "written communication",
                  "public speaking", "soft skills", "ppt", "powerpoint", "storytelling", "voice and accent"],
         why="For trainer roles this is assessed live in the interview via a demo session.",
         learn=["Free: practise a 10-min demo session, record it on your phone, watch for fillers",
                "Free: Toastmasters guest sessions; 'BBC Learning English - Business English'",
                "Prepare 3 demo topics you can teach cold for 10 minutes"],
         link="https://www.toastmasters.org/ ",
         proof="Nail the demo round - most trainer offers are decided there.",
         adjacent=["trainer", "session", "demo", "deliver", "facilitat", "present", "nht", "english"],
         tools=["Free: Toastmasters (guest sessions) or record a 10-min session on your phone and self-review",
                "AI: ChatGPT - 'Act as a tough interview panel; give me 5 trainer demo-round questions + rate my answer'",
                "Free: 'BBC Learning English - Business English' + practice 3 demo topics cold"]),

    dict(key="AI tools for L&D (ChatGPT/Gemini for content)", roles=["trainer", "training manager", "l&d"],
         aliases=["ai", "genai", "chatgpt", "gemini", "copilot", "prompt", "automation",
                  "digital transformation", "ai in learning"],
         why="2025-26 JDs increasingly ask this; it is a cheap differentiator right now.",
         learn=["Free: Google 'Prompting Essentials' / Microsoft Copilot learning path",
                "Do it: use AI to draft assessments and role-play scripts, then note the time saved"],
         link="https://learnprompting.org/ ",
         proof="'I cut content development time ~40% using AI-assisted drafting for assessments and role-plays.'",
         adjacent=["chatgpt", "gemini", "ai", "content", "draft", "prompt", "tool"],
         tools=["Free: ChatGPT (free tier) or Google Gemini or Microsoft Copilot - all do text + docs",
                "Course: Google 'Prompting Essentials' / learnprompting.org (free) - 1-2 hrs",
                "Do it: use AI to draft assessments, role-play scripts, quiz banks; keep a before/after time log"]),

    dict(key="Vendor & training budget management", roles=["training manager", "l&d"],
         aliases=["budget", "vendor", "cost per trainee", "procurement", "p&l", "cost management",
                  "external partner", "rfp"],
         why="Separates 'senior trainer' from 'training manager' on paper.",
         learn=["Free: learn 'cost per trainee' and 'training spend as % of payroll' benchmarks",
                "Do it: build a costed plan for one program (trainer hours, material, venue, opportunity cost)"],
         link="https://www.atd.org/capability-model ",
         proof="'I managed a Rs. X lakh annual training budget / reduced cost per trainee by Y%.'",
         tools=["Free: Excel - build a cost model (trainer hours, material, venue, opportunity cost) for one program",
                "AI: ChatGPT - 'From this program's cost lines, compute cost-per-trainee and 3 cost-saving levers'",
                "Learn: 'cost per trainee' and 'training spend as % of payroll' benchmarks (ATD)"]),
]


def role_focus(role_key):
    return [s for s in SKILLS if role_key in s["roles"]]


ROLE_LABELS = {
    "trainer": "Trainer",
    "training manager": "Training Manager",
    "l&d": "L&D Manager",
    "rsm": "Regional Sales Manager",
}
